[project]
name = "kai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kang", email = "lowkangxuan@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "openai>=3.16.2",
    "pydantic>=2.13.5",
    "uvicorn>=0.53.0",
]

[project.scripts]
kai = "kai:main"

[tool.uv]
package = false

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
